threepointers = input("How many threepointers did James Harden make? ")
threepointers = int(threepointers)
twopointers = input("How many twopointers did James Harden make? ")
twopointers = int(twopointers)
freethrows = input("How many freethrows did James Harden make? ")
freethrows = int(freethrows)
threepointscore = (threepointers * 3)
twopointscore = (twopointers * 2)
points = (threepointscore + twopointscore + freethrows)
print("James Harden scored " + str(points) + " points.")